### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by AlexanderFromEarth** [maximberdyshev/todos-f#1]
В целом код приятный (хоть его и мало) хорошо разбил компоненты и страницы. Есть несколько моментов, которые можно улучшить несмотря на законченность/незаконченность проекта. Не пугайся, если считаешь, что много, у меня на ревью бывало по 20 уникальных предложений по улучшению. Всё приходит с опытом. Если всё же решишь доделать, можешь написать гляну.)

1. Лучше указать null в таком случае
https://github.com/maximberdyshev/todos-f/blob/eb1178e3a153288c62b62371b5221d04d57e4615/src/pages/Login.jsx#L8
2. Лучше в context засунуть логику
https://github.com/maximberdyshev/todos-f/blob/eb1178e3a153288c62b62371b5221d04d57e4615/src/components/MainForm.jsx#L9
https://github.com/maximberdyshev/todos-f/blob/eb1178e3a153288c62b62371b5221d04d57e4615/src/components/Navbar/MyNavbar.jsx#L14-L15
https://github.com/maximberdyshev/todos-f/blob/eb1178e3a153288c62b62371b5221d04d57e4615/src/components/AuthWindow/AuthBtn.jsx#L13-L20
3. Лучше не за счет классов видимость модалки обеспечивать в React, а за счет условий отрисовывать или нет
https://github.com/maximberdyshev/todos-f/blob/eb1178e3a153288c62b62371b5221d04d57e4615/src/components/UI/modal/MyModal.module.css#L1-L23
https://github.com/maximberdyshev/todos-f/blob/eb1178e3a153288c62b62371b5221d04d57e4615/src/components/UI/modal/MyModal.jsx#L6-L8
4. Лучше поставить false, а не переключать. Мало ли какой баг всплывет и при нажатии на logout пользователь будет иметь статус "авторизован" по состоянию
https://github.com/maximberdyshev/todos-f/blob/eb1178e3a153288c62b62371b5221d04d57e4615/src/components/Navbar/MyNavbar.jsx#L13
5. Всё верно, что не реализована. В рамках безопасности мы обычно скрываем от него информацию о том пароль или логин неверны
https://github.com/maximberdyshev/todos-f/blob/eb1178e3a153288c62b62371b5221d04d57e4615/src/components/AuthWindow/AuthBtn.jsx#L22-L24
6. Для таких данных context не нужен, так как по хорошему эти данные относятся только к моменту авторизации и более нигде не нужны
https://github.com/maximberdyshev/todos-f/blob/eb1178e3a153288c62b62371b5221d04d57e4615/src/components/AuthWindow/AuthInput.jsx#L6
7. Лучше деструктуризовать пропсы
https://github.com/maximberdyshev/todos-f/blob/eb1178e3a153288c62b62371b5221d04d57e4615/src/components/Todo/TodoItem.jsx#L6
8. Лучше содержимое файла с роутам перенести в App.js, так как странно получается, что компонент обращается к страницам

**Comment by maximberdyshev** [comment]
1. Исправил.
2. В работе.
3. В работе.
4. В работе.
5. В работе.
6. В работе.
7. Исправил. Предполагаю, что лучше указывать пропсы явно, для лучшей читаемости? )
8. Исправил. Согласен) Перенес маршруты в App.js

Дополнительно:
- вынес стили компонентов AuthWindow и Todo в соответствующие папки.

**Comment by AlexanderFromEarth** [comment]
4. Я имел ввиду сделать так, чтобы при вызове функции из контекста, у тебя велась работа с localStorage и при создании контекста актуальная подтягивалась. Все верно касательно того, что перерендер всех компонентов происходит в случае авторизации логично, что скорее всего придётся изменить всё.) Для других общих хранилищ логики можно поступать следующим образом, если использовать контекст: оборачивать в него только те компоненты, которые реально зависят от его данных. Так можно избежать перерендеров. А вообще лучше использовать mobX, redux, recoil etc.

**Comment by AlexanderFromEarth** [comment]
5. Да, конкретной подсказки быть не должно, иначе злоумышленник может понять, что он подобрал логин и будет подбирать пароли, а это вызовет кучу проблем.

**Comment by AlexanderFromEarth** [comment]
6. Зависит от логики. Логика может быть поведения самого компонента, например компонент преобразует введённые данные, так что в родитель с помощью функции обратного вызова он отдаёт изменённые, а у себя хранит исходные. Если же логика относится к совокупности компонентов, то она определяется в родителе и так может быть поднята вверх по иерархии до самой страницы в зависимости от её обобщённости/конкретности.

**Comment by AlexanderFromEarth** [comment]
7. Да, в основном для читаемости, также статические анализаторы могут подсказывать при использовании компонента, какие пропсы есть.
